In [54]:
from sklearn import cross_validation, datasets

In [55]:
import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [56]:
iris = datasets.load_iris()

In [57]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data,
                                                                                    iris.target,
                                                                                    test_size=0.3)
#train_data, test_data -части нашей выборки для обучения и для теста
#train_labels, test_labels - метки объектов из обучающей и тестовой выборки

In [58]:
#тестовая выборка - 0.3
float(len(test_labels) / len(iris.data))

0.3

In [59]:
print(train_data.shape, "shape train_data")
print(test_data.shape, "shape test_data")

(105, 4) shape train_data
(45, 4) shape test_data


## Стратегия кросс-валидации

### kFold

In [60]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds=5):
    print (train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [61]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds=2, shuffle=True, random_state=5):
    print(train_indices, test_indices)

[0 1 3 6 8] [2 4 5 7 9]
[2 4 5 7 9] [0 1 3 6 8]


### StratifiedKFold

In [62]:
target = np.array([0]*5 + [1]*5)
print(target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds=2, shuffle=True,
                                                                    random_state=2):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[0 3 7 8] [1 2 4 5 6 9]
[1 2 4 5 6 9] [0 3 7 8]


In [63]:
target = np.array([0, 1]*5)
print(target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds=2, shuffle=True,
                                                                    random_state=0):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[6 7 8 9] [0 1 2 3 4 5]
[0 1 2 3 4 5] [6 7 8 9]


## ShuffleSplit

In [64]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter=10, test_size=0.2):
    print (train_indices, test_indices)

[7 5 9 8 0 1 6 2] [4 3]
[2 1 6 7 5 4 9 3] [8 0]
[7 0 1 9 6 3 4 2] [5 8]
[0 9 6 2 8 4 7 5] [3 1]
[9 4 6 8 0 1 5 3] [2 7]
[6 0 9 1 4 7 2 8] [5 3]
[1 9 0 3 7 6 8 2] [5 4]
[6 0 1 3 9 4 2 5] [7 8]
[0 6 5 4 7 2 8 9] [3 1]
[2 5 3 9 1 7 8 4] [0 6]


In [66]:
target = np.array([0] * 5 + [1] * 5)
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter=10, test_size=0.2):
    print(train_indices, test_indices)

[3 6 5 7 1 4 2 9] [0 8]
[5 1 7 8 4 0 3 9] [2 6]
[3 7 8 1 6 5 4 0] [9 2]
[5 7 2 1 4 0 8 9] [3 6]
[7 8 1 3 0 9 6 4] [5 2]
[1 3 0 9 7 2 5 6] [4 8]
[0 9 2 5 8 1 4 7] [3 6]
[2 8 4 0 5 1 9 7] [3 6]
[8 6 0 9 1 2 7 4] [3 5]
[6 2 5 1 0 4 7 9] [8 3]


## Leave-One-Out

In [67]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print(train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
