# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import cross_validation, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [4]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [5]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

SyntaxError: invalid syntax (<ipython-input-5-bb0d42fd6e61>, line 1)

In [6]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-6-366f8cb9ba1c>, line 1)

In [7]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-7-58915b12905a>, line 1)

### Стратегии проведения кросс-валидации

#### KFold

In [9]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5):
    print (train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [10]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print (train_indices, test_indices)

[0 3 5 8 9] [1 2 4 6 7]
[1 2 4 6 7] [0 3 5 8 9]


In [11]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print (train_indices, test_indices)

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [12]:
target = np.array([0] * 5 + [1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print (train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [13]:
target = np.array([0, 1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print (train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[2 5 6 9] [0 1 3 4 7 8]
[0 1 3 4 7 8] [2 5 6 9]


#### ShuffleSplit

In [14]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print (train_indices, test_indices)

[3 9 4 7 6 0 2 5] [8 1]
[9 8 7 4 2 5 6 1] [0 3]
[7 5 4 0 8 3 6 1] [9 2]
[6 2 4 3 8 9 0 5] [1 7]
[4 6 8 9 0 1 3 2] [7 5]
[7 0 3 5 6 4 8 9] [1 2]
[5 6 4 3 1 7 2 9] [8 0]
[4 8 5 6 1 0 2 7] [9 3]
[8 3 1 6 0 2 7 9] [5 4]
[0 7 2 5 1 9 4 8] [3 6]


#### StratifiedShuffleSplit

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

#### Leave-One-Out

In [ ]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators